language: node_js
node_js:
- '6'
sudo: required
services:
- docker
before_install:
- cd $TRAVIS_BUILD_DIR
install:
- "./tools/travis/setupscan.sh"
- cd $TRAVIS_BUILD_DIR
- "./tools/travis/setup.sh"
- cd $TRAVIS_BUILD_DIR
script:
- "./tools/travis/scancode.sh"
- cd $TRAVIS_BUILD_DIR
- "./tools/travis/build.sh"
deploy:
  provider: npm
  email: apacheopenwhisk@gmail.com
  api_key:
    secure: DBM6VScujsLbzNKOsZHX6/u+S7NKFbuzU/iKt20HmobUUDrCEOhL9aY+ojAw3mFktaM6M7U6fq8uazvXtqcsIy5j3prAIelZyJep1Tl1zkLptdphoa8DkDP5ErbjwN9LMZBs74PRKZDDsKJfgMDYHMw05gYsnDXhZ49V+2JCuJ5e3jidVAeXsdcF3pkxc5+YLk4IQ/ryk6bSG2VTA0U+Opcck7Z2S6JrVwvbJsLJcknsYXMMq4fttRIAXcG+yw8F8vndN9Ge50EJLsazHzyIxCPZhBNwTU9T7vwCB3XtepP+ghbb0CVI6DvfXPwPzw1iQDSOkKk8aFt77jdGV4HEdFitpukbzhmKEF6zd0SDwLkvPwafZhNNAchhv/VganFFj/ebPFtXMxI1SgvPGTsDIj6s2D6JGTgZN2BSzKRfUf0s05Dozx+2ZeZ3n61DykUK8xFoamlVZFD7iim8s1hg541xwQ/dtr3/zQ6gp5riQF8tXh5sOAiwVdLoZTpIvN9hgwB9RJ/GCxj7ug+WGkZmDHcPtCPO/zvjQc9rLVLC6o16NocpPwErGtez3MALwSh+7hLNG7ch/tSZzi3Ej81XRZpWyVY2pDq9oObxTWMFKfOvWOjKbrAnkOS1EA9djFsC5e46HlWpZlO16wbLZj6T3DT9GhuGxR//XCTwMtyCkuk=
  on:
    tags: true
    repo: karanrk/incubator-openwhisk-client-js
 
branches:
  only:
   - openwhisk-proxy
